"""phase1 session chat upload

Revision ID: 58f618abac81
Revises: 7d8e029a070f
Create Date: 2026-03-12 15:53:43.754362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58f618abac81'
down_revision = '7d8e029a070f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_tags',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('tag', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'tag', name='uq_session_tags_session_tag')
    )
    with op.batch_alter_table('session_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_tags_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_tags_tag'), ['tag'], unique=False)

    op.create_table('chat_attachments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('message_id', sa.String(length=64), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=32), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    with op.batch_alter_table('chat_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_attachments_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_attachments_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_attachments_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('model_name', sa.String(length=64), server_default='qwen-plus', nullable=False))
        batch_op.add_column(sa.Column('retrieval_mode', sa.String(length=32), server_default='hybrid', nullable=False))
        batch_op.add_column(sa.Column('web_search_enabled', sa.Boolean(), server_default=sa.false(), nullable=False))

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.alter_column('model_name', server_default=None)
        batch_op.alter_column('retrieval_mode', server_default=None)
        batch_op.alter_column('web_search_enabled', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('web_search_enabled')
        batch_op.drop_column('retrieval_mode')
        batch_op.drop_column('model_name')
        batch_op.drop_column('summary')

    with op.batch_alter_table('chat_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_attachments_user_id'))
        batch_op.drop_index(batch_op.f('ix_chat_attachments_session_id'))
        batch_op.drop_index(batch_op.f('ix_chat_attachments_message_id'))

    op.drop_table('chat_attachments')
    with op.batch_alter_table('session_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_tags_tag'))
        batch_op.drop_index(batch_op.f('ix_session_tags_session_id'))

    op.drop_table('session_tags')
    # ### end Alembic commands ###
